# Neuronal Network in plain python

Description
singel Layer perceptron (feedforward neural network)


## Version Check

### Expected Language/Library versions:
Python version:
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

NumPy version:
1.13.3

TensorFlow version:
1.4.1

scikit-learn version:
0.19.1

### System Versions

In [1]:
import sys
import numpy as np
import tensorflow as tf
import sklearn

In [3]:
print("Python version:")
print(sys.version)

print("")

print("NumPy version:")
print(np.__version__)

print("")

print("TensorFlow version:")
print(tf.__version__)

print("")

print("scikit-learn version:")
print(sklearn.__version__)

Python version:
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

NumPy version:
1.13.3

TensorFlow version:
1.4.1

scikit-learn version:
0.19.1


## 

In [ ]:
# lets go

# layer 0
input1 = 0;
w1 = 5; # how to choose the weight range?????
b1 = 1; # how to choose the bias range?????
input2 = 0;
w1 = -5;
b2 = 1;

# print(input1, input2)

# hidden layer 1
# has 3 neurons

# instead call it activation function?

#def create_neuron(dict):
#    return (np.random.randint(11))/10

#def sigmoid(x):
#    return 1 / (1 + math.exp(-x))

#def activation(inputs=[],w,b):
#    sumOfWeightsMultInputs = 1+5-8;
#    bias=5;
#    return sigmoid(sumOfWeights + bias);






#print(create_neuron())

mapping = [
    
];

0
0
= s(w1 * i1 + b1) = 0

0
1
= ... = 0

1
0
= ... = 1

1
1
= ... = 1


[
    [0],
    [0]
]

bsp:
[
[1,2,3],
[4,5,6]
]

================

i1=0
i2=1

#i1
[
    [0],
    [0],
    [0],  
]

*

[
    [w0],
    [w1],
    [w2],
]

+

#i2
[
    [1],
    [1],
    [1],  
]

*

[
    [w0],
    [w1],
    [w2],
]

+

[
    [b0],
    [b1],
    [b2]
]

=

0 ... 1

====================

[
    [w0*i0 + w0+i1],
    [w1*i0 + w1+i1],
    [w2*i0 + w2+i3],
]

+

[
    [b0],
    [b1],
    [b2]
]


====================

#expect
i0 , i1

iw0, iw1

lw0, lw1, lw2

b0,b1,b2

====

Felix:

inputs
i0, i1,

neuron
n0, n1, n2

bias
b0,b1,b2

weights
wi0n0, wi0n1, wi0n2, wi1n0, wi1n1, wi1n2

====

3 * neuron in hidden layer 1

outN0 = w0 * i0    +  w0 * i1    + b0

outN1 = w1 * i0    +  w1 * i1    + b1

outN0 = w2 * i0    +  w2 * i1    + b2


=================

input layer
i00, i10

weights
w00, w01 => weight edges from input layer to 1st neuron of 1st hidden layer

outN0 = w00*i00 + w01*i10 + b0

sidenote
2 inputs + 1 neuron = 2 edges
2 inputs + 2 neuron = 4 edges
2 inputs + 3 neuron = 6 edges

weights2
w10, w11,

outN1 = w10*i00 + w11*i10 + b1

weights3
w20, w21,

outN2 = w20*i00 + w21*i10 + b2

consculusion

outN0 = w00*i00 + w01*i10 + b0
outN1 = w10*i00 + w11*i10 + b1
outN2 = w20*i00 + w21*i10 + b2













## Siraj Raval implementation

In [22]:

import time

#variables

n_hidden = 10
n_in = 10
n_out = 10
n_samples = 300

#hyperparameters
learning_rate = 0.01
momentum = 0.9 #for lowering loss ?

# non deterministic seeding
np.random.seed(0) #make sure generate every time the same random data

# truns numbers into probability
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def tanh_prime(x):
    return 1 - np.tanh(x)**2

# x = input 
# t = transpose ??? helps matrics multiplication
# V,W = layers
# bv, bw = biases
#
def train(x, t, V, W, bv, bw):
    
    # forward propagation -- matrics multiplication + bias
    A = np.dot(x, V) + bv
    Z = np.tanh(A)

    B = np.dot(Z, W) + bw
    Y = sigmoid(B)
    
    # backward propagation
    Ew = Y - t #errors???
    Ev = tanh_prime(A) * np.dot(W, Ew)
    
    #predict our loss
    dW = np.outer(Z, Ew)
    dV = np.outer(x, Ev)
    
    #"cross entropy" as loss (good for classification)
    loss = -np.mean(t * np.log(Y) + (1 - t) * np.log(1-Y))
    loss = -np.mean ( t * np.log(Y) + (1 - t) * np.log(1 - Y) )
    
    return loss, (dV, dW, Ev, Ew)

def predict(x, V, W, bv, bw):
    A = np.dot(x, V) + bv
    B = np.dot(np.tanh(A), W) + bw
    return (sigmoid(B) > 0.5).astype(int)


In [26]:

# create layers
V = np.random.normal(scale=0.1, size=(n_in, n_hidden))
W = np.random.normal(scale=0.1, size=(n_hidden, n_out))

bv = np.zeros(n_hidden);
bw = np.zeros(n_out);

params = [V, W, bv, bw]

# generate our data
X = np.random.binomial(1, 0.5, (n_samples, n_in))
# calc transpose
T = X ^ 1 #bitwise xor

print(X[0])
print()
print(T[0])


[1 1 0 1 1 1 1 0 0 0]

[0 0 1 0 0 0 0 1 1 1]


In [29]:

# training
for epoch in range(100):
    err = []
    upd = [0]*len(params)
    
    t0 = time.clock()
    # for each data point, update our weights
    for i in range(X.shape[0]):
        loss,grad = train(X[i], T[i], *params)
        #update loss
        for j in range(len(params)):
            params[j] -= upd[j]
            
        for j in range(len(params)):
            upd[j] = learning_rate * grad[j] + momentum * upd[j]
        
        err.append(loss)
    
    print('Epoch: %d, Loss: %.8f, Time: %.4fs'%(epoch, np.mean(err), time.clock()-t0 ) )
        

Epoch: 0, Loss: 0.00121482, Time: 0.0598s
Epoch: 1, Loss: 0.00120214, Time: 0.0313s
Epoch: 2, Loss: 0.00118972, Time: 0.0326s
Epoch: 3, Loss: 0.00117755, Time: 0.0347s
Epoch: 4, Loss: 0.00116561, Time: 0.0308s
Epoch: 5, Loss: 0.00115392, Time: 0.0302s
Epoch: 6, Loss: 0.00114245, Time: 0.0321s
Epoch: 7, Loss: 0.00113120, Time: 0.0459s
Epoch: 8, Loss: 0.00112017, Time: 0.0384s
Epoch: 9, Loss: 0.00110934, Time: 0.0352s
Epoch: 10, Loss: 0.00109872, Time: 0.0364s
Epoch: 11, Loss: 0.00108830, Time: 0.0346s
Epoch: 12, Loss: 0.00107807, Time: 0.0367s
Epoch: 13, Loss: 0.00106802, Time: 0.0466s
Epoch: 14, Loss: 0.00105815, Time: 0.0368s
Epoch: 15, Loss: 0.00104847, Time: 0.0282s
Epoch: 16, Loss: 0.00103895, Time: 0.0277s
Epoch: 17, Loss: 0.00102960, Time: 0.0295s
Epoch: 18, Loss: 0.00102042, Time: 0.0303s
Epoch: 19, Loss: 0.00101139, Time: 0.0301s
Epoch: 20, Loss: 0.00100252, Time: 0.0437s
Epoch: 21, Loss: 0.00099380, Time: 0.0346s
Epoch: 22, Loss: 0.00098523, Time: 0.0291s
Epoch: 23, Loss: 0.00

In [50]:

# try to predict something
x = np.random.binomial(1, 0.5, n_in)

print("XOR prediction")
print(x)
print(predict(x, *params))


XOR prediction
[0 0 0 0 0 0 0 1 0 0]
[1 1 1 1 1 1 1 0 1 1]
3


In [58]:
def double(x):
    return 2*x

def pipeOld(arg, *funcs):
    for f in funcs:
        arg = f(arg)
    return arg

print(pipe(2, double, str))

4


In [65]:
from functools import reduce

def double(x):
    return 2*x

def pipe(arg, *funcs):
    return reduce( (lambda a, b: b(a)), funcs, arg )

print(pipe(2, double, double, str))

8
