# simple 0 1 inverter
has one input (1 or 0) and two (?) outputs

In [3]:
import os
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import torch.optim as optim



In [4]:
class SimpleNet(torch.nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        
        #add layers
        
        #add input layer
        inLayer_input_features_count = 1
        inLayer_output_features_count = 2
        self.inputLayerLin = torch.nn.Linear(inLayer_input_features_count, inLayer_output_features_count)
        
        #add hidden layer
        hiddLay1_in_features_count = inLayer_output_features_count
        hiddLay1_out_features_count = 2
        self.hiddLay1 = torch.nn.Linear(hiddLay1_in_features_count, hiddLay1_out_features_count)
        
        #add output layer
        outLayer_in_features_count = hiddLay1_out_features_count
        outLayer_out_features_count = 1
        self.outLayer = torch.nn.Linear(outLayer_in_features_count, outLayer_out_features_count)
        
        
    def forward(self, x):
        x = self.inputLayerLin(x)
        x = F.sigmoid(x)
        x = self.hiddLay1(x)
        x = F.sigmoid(x)
        x = self.outLayer(x)
        #print("SimpleNet ... forward ... x of outLayer", x)
        x = F.sigmoid(x)
        return x
        


In [5]:
inputs = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,])
targets = inputs ^ 1

inputs = list(map(lambda s: Variable(torch.Tensor([s])), inputs))
targets = list(map(lambda s: Variable(torch.Tensor([s])), targets))


print(inputs)
print(targets)

[tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.])]
[tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 0.]), tensor([ 1.]), tensor([ 0.]), tensor([ 1.]), tensor([ 1.])]


In [6]:
def train(net, inputs, targets, epochs=10):
    #MySimpleNet.train()
    criterion = nn.MSELoss()
    optimizer = optim.SGD(net.parameters(), lr=0.01)
    for idx in range(0, epochs):
        for single_input, single_target in zip(inputs, targets):
            optimizer.zero_grad()   # zero the gradient buffers
            output = net(single_input)
            loss = criterion(output, single_target)
            loss.backward() # <= what happens here?
            optimizer.step()    # Does the update
        if idx % (epochs / 10) == 0:
            print("Epoch {: >8} Loss: {}".format(idx, loss.data.numpy()))

In [22]:
MySimpleNet = SimpleNet()
print(MySimpleNet(inputs[0]))

tensor([ 0.5876])


In [23]:
train(MySimpleNet, inputs, targets, epochs=1300)

Epoch        0 Loss: 0.17840322852134705
Epoch      130 Loss: 0.2515670657157898
Epoch      260 Loss: 0.250333309173584
Epoch      390 Loss: 0.24906717240810394
Epoch      520 Loss: 0.24698154628276825
Epoch      650 Loss: 0.24170616269111633
Epoch      780 Loss: 0.22322389483451843
Epoch      910 Loss: 0.15574169158935547
Epoch     1040 Loss: 0.059517599642276764
Epoch     1170 Loss: 0.023411553353071213


In [24]:
print(inputs[0])
print(MySimpleNet(inputs[0]))
print(inputs[1])
print(MySimpleNet(inputs[1]))

tensor([ 1.])
tensor([ 0.1110])
tensor([ 0.])
tensor([ 0.8883])


0
